import { formatTopicConfigForPrompt, getLaunchProductIds, getPaidAnalysisPremiumDepthContract, getPaidAnalysisTopicConfig } from "../app/lib/paidAnalysisTopicConfig";
import { buildPaidAnalysisDetailPromptV4 } from "../app/lib/paidAnalysisDetailPrompt";
import { getPremiumProduct } from "../app/lib/premiumProductRegistry";
import { validatePremiumDepthSiblingDistinction } from "../app/lib/paidAnalysisV4QualityValidators";
function assert(condition: boolean, message: string): void { if (!condition) throw new Error(`FAIL: ${message}`); }
const ids = ["study-learning-strategy","study-exam-preparation","study-focus-routine","study-credential-decision","business-startup-readiness","business-expansion-control","business-client-relationship","business-team-management"] as const;
const pairs = [["study-learning-strategy","study-exam-preparation"],["study-exam-preparation","study-credential-decision"],["business-startup-readiness","career-freelance-transition"],["business-team-management","career-leadership-readiness"],["business-client-relationship","career-workplace-relationships"]] as const;
const base = { analysisType: "테스트 분석", birthData: "birth", originalChart: "chart", coreInterpretation: "core", fortuneTiming: "timing", sajuSummary: "summary", currentFortuneFlow: "flow" };
const launch = getLaunchProductIds(); assert(launch.length === 48, "Batch 5 launch count must be 48"); assert(new Set(launch).size === launch.length, "launch IDs unique");
for (const id of ids) { const config = getPaidAnalysisTopicConfig(id); if (!config) throw new Error(`FAIL: missing ${id}`); assert(Boolean(getPremiumProduct(id)), `${id} registry`); assert(config.userQuestion.trim().length > 0 && config.evidenceFocus.length >= 3 && config.actionFocus.length >= 3 && config.prohibitedClaims.length > 0 && config.excludedFocus?.length === 3, `${id} contract completeness`); assert(config.requiredInsights.length === 4 && new Set(config.requiredInsights.map(i => i.id)).size === 4, `${id} four unique insights`); const prompt = buildPaidAnalysisDetailPromptV4({ ...base, productId: id }); assert(prompt.includes(config.userQuestion) && prompt.includes("[상품 중심 추론 계약]"), `${id} generic prompt`); for (const insight of config.requiredInsights) assert(prompt.includes(insight.prompt), `${id} insight prompt`); const formatted = formatTopicConfigForPrompt(config); for (const claim of config.prohibitedClaims) assert(formatted.includes(claim), `${id} safety`); }
for (const [leftId, rightId] of pairs) { const left = getPaidAnalysisTopicConfig(leftId); const right = getPaidAnalysisTopicConfig(rightId); if (!left || !right) throw new Error(`FAIL: ${leftId}/${rightId}`); assert(left.userQuestion !== right.userQuestion, `${leftId}/${rightId} question`); assert(JSON.stringify(left.requiredInsights) !== JSON.stringify(right.requiredInsights), `${leftId}/${rightId} mechanism`); assert(JSON.stringify(left.actionFocus) !== JSON.stringify(right.actionFocus), `${leftId}/${rightId} action`); assert(validatePremiumDepthSiblingDistinction(getPaidAnalysisPremiumDepthContract(left), getPaidAnalysisPremiumDepthContract(right)).ok, `${leftId}/${rightId} positive ownership`); }
console.log("paid-analysis-v4-catalog-batch-5-regression passed ✓");