import { createServer, type Server } from "node:http";
import { readFileSync } from "node:fs";
import { spawn, type ChildProcess } from "node:child_process";
import { randomUUID } from "node:crypto";

const API = "http://127.0.0.1:55321";
const NEXT = "http://127.0.0.1:3107";
const MOCK = "http://127.0.0.1:55443/v1";
const SECRET = "r10f-disposable-secret";
const PREFIX = "step-57d-45d-r10f-";
function assert(value: boolean, message: string): void { if (!value) throw new Error(`FAIL: ${message}`); }
function envFile(path: string): Record<string, string> { const result: Record<string, string> = {}; for (const line of readFileSync(path, "utf8").split(/\r?\n/)) { const m = line.match(/^([A-Z0-9_]+)=(.*)$/); if (m) result[m[1]] = m[2].trim().replace(/^(['"])(.*)\1$/, "$2"); } return result; }
function loadRuntime(): void { const v = envFile("supabase-r6-disposable/supabase/.temp/start-secrets/supabase_edge_runtime_unboda-r6-disposable/env/docker.env"); assert(v.SUPABASE_INTERNAL_HOST_PORT === "55321", "disposable API required"); assert(v.SUPABASE_DB_URL.includes("supabase_db_unboda-r6-disposable"), "disposable DB required"); process.env.NEXT_PUBLIC_SUPABASE_URL = API; process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY = v.SUPABASE_INTERNAL_PUBLISHABLE_KEY; process.env.SUPABASE_SERVICE_ROLE_KEY = v.SUPABASE_SERVICE_ROLE_KEY; }

type Mode = "valid" | "mismatch" | "temporary";
type Fixture = { userId: string; profileId: string; orderId: string; workflowId: string; mode: Mode };

async function main(): Promise<void> {
  loadRuntime();
  const { createAdminClient } = await import("../app/lib/supabase/admin");
  const db = createAdminClient();
  const oldUsers = (await db.auth.admin.listUsers({ perPage: 1000 })).data.users.filter((u) => u.email?.startsWith(PREFIX));
  for (const u of oldUsers) await db.auth.admin.deleteUser(u.id);
  await cleanup();
  const before = await db.from("orders").select("id"); assert((before.data ?? []).length === 0, "disposable baseline must be empty");
  const fixtures: Fixture[] = [];
  const providerModes = new Map<string, Mode>();
  let providerLookupCalls = 0; let providerCancellationCalls = 0; let next: ChildProcess | undefined; let mock: Server | undefined;
  async function fixture(label: string, mode: Mode, status = "REFUND_PROCESSING", due = true): Promise<Fixture> {
    const user = (await db.auth.admin.createUser({ email: `${PREFIX}${randomUUID()}@local.test`, password: "r10f-local-password", email_confirm: true })).data.user; assert(Boolean(user), `${label}: user`);
    const profile = (await db.from("profiles").insert({ user_id: user!.id, label, relationship_type: "other", birth_date: "1990-01-01", birth_time: "12:00:00", gender: "male", calendar_type: "solar", is_leap_month: false }).select("id").single()).data as { id: string };
    const order = (await db.from("orders").insert({ user_id: user!.id, profile_id: profile.id, product_id: "money-leak-risk", amount: 16900, status: "paid", payment_provider: "toss", transaction_id: `r10f-${fixtures.length}`, paid_at: new Date().toISOString() }).select("id").single()).data as { id: string };
    const payment = (await db.from("toss_payment_records").insert({ order_id: order.id, payment_key: `pay_r10f_${fixtures.length}`, provider_order_id: order.id, expected_amount: 16900, confirmed_amount: 16900, currency: "KRW", provider_status: "DONE", reconciliation_status: "externally_confirmed" }).select("id").single()).data as { id: string };
    const purchase = (await db.from("purchases").insert({ user_id: user!.id, profile_id: profile.id, product_id: "money-leak-risk", order_id: order.id }).select("id").single()).data as { id: string };
    await db.from("entitlements").insert({ user_id: user!.id, profile_id: profile.id, resource_id: "money-leak-risk", resource_type: "paid_analysis", is_active: true, source: "purchase", purchase_id: purchase.id });
    const workflow = (await db.from("refund_workflows").insert({ order_id: order.id, payment_record_id: payment.id, user_id: user!.id, profile_id: profile.id, product_id: "money-leak-risk", requested_amount: 16900, currency: "KRW", reason_category: "CHANGE_OF_MIND", status, next_retry_at: due ? new Date(Date.now() - 1000).toISOString() : new Date(Date.now() + 3600000).toISOString(), ...(status === "REFUND_COMPLETED" ? { provider_status: "CANCELED", provider_cancellation_reference: "tx-complete" } : {}) }).select("id").single()).data as { id: string };
    const value = { userId: user!.id, profileId: profile.id, orderId: order.id, workflowId: workflow.id, mode }; fixtures.push(value); providerModes.set(order.id, mode); return value;
  }
  async function cleanup(): Promise<void> { const users = (await db.auth.admin.listUsers({ perPage: 1000 })).data.users.filter((u) => u.email?.startsWith(PREFIX)); const residue = (await db.from("orders").select("user_id").like("transaction_id", "r10f-%")).data ?? []; const userIds = new Set([...users.map((u) => u.id), ...residue.map((row: { user_id: string }) => row.user_id)]); for (const userId of userIds) { const orders = (await db.from("orders").select("id").eq("user_id", userId)).data ?? []; const ids = orders.map((x: { id: string }) => x.id); await db.from("refund_workflows").delete().eq("user_id", userId); if (ids.length) await db.from("toss_payment_records").delete().in("order_id", ids); await db.from("purchases").delete().eq("user_id", userId); await db.from("entitlements").delete().eq("user_id", userId); await db.from("orders").delete().eq("user_id", userId); await db.from("profiles").delete().eq("user_id", userId); await db.auth.admin.deleteUser(userId); } }
  let finalSummary: Record<string, unknown> | undefined;
  try {
    mock = createServer((req, res) => { if (!req.url?.startsWith("/v1/payments/orders/")) { res.writeHead(404); res.end(); return; } providerLookupCalls++; const orderId = decodeURIComponent(req.url.slice("/v1/payments/orders/".length)); const mode = providerModes.get(orderId) ?? "temporary"; res.setHeader("content-type", "application/json"); if (mode === "temporary") { res.writeHead(503); res.end(JSON.stringify({ code: "TEMPORARY" })); return; } const amount = mode === "mismatch" ? 15000 : 16900; res.end(JSON.stringify({ paymentKey: `pay_mock_${orderId}`, orderId, totalAmount: amount, status: "CANCELED", currency: "KRW", cancels: [{ transactionKey: `tx_${orderId}`, cancelAmount: amount, cancelStatus: "DONE", canceledAt: new Date().toISOString(), refundableAmount: 0 }] })); });
    await new Promise<void>((resolve) => mock!.listen(55443, "127.0.0.1", resolve));
    const runtime = { ...process.env, NEXT_PUBLIC_SUPABASE_URL: API, SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY, PAYMENT_RECONCILIATION_SECRET: SECRET, TOSS_SECRET_KEY: "test_sk_r10f_disposable", NEXT_PUBLIC_TOSS_CLIENT_KEY: "test_ck_r10f_disposable", TOSS_ENVIRONMENT: "sandbox", TOSS_API_BASE_URL: MOCK, PORT: "3107" };
    next = spawn(process.execPath, ["node_modules/next/dist/bin/next", "dev", "-p", "3107"], { env: runtime, stdio: "ignore", cwd: process.cwd() });
    for (let i = 0; i < 60; i++) { try { const response = await fetch(`${NEXT}/api/internal/payments/refunds/reconcile`); if (response.status === 401) break; } catch { /* wait for disposable Next */ } await new Promise((resolve) => setTimeout(resolve, 500)); }
    const call = async (auth?: string) => { const response = await fetch(`${NEXT}/api/internal/payments/refunds/reconcile`, { headers: auth ? { Authorization: `Bearer ${auth}` } : {} }); const text = await response.text(); for (const forbidden of ["paymentKey", "TOSS_SECRET_KEY", "SUPABASE_SERVICE_ROLE_KEY", "PAYMENT_RECONCILIATION_SECRET", "Authorization", "claimToken", "cancels", "cardNumber", "bank"]) assert(!text.includes(forbidden), `response leaks ${forbidden}`); return { response, body: JSON.parse(text) as Record<string, unknown> }; };
    const unauthorized = await call(); assert(unauthorized.response.status === 401, "unauthorized request blocked"); assert(Boolean(unauthorized.body.error), "unauthorized response safe");
    const empty = await call(SECRET); assert(empty.response.ok && empty.response.headers.get("cache-control") === "no-store", "authorized empty run and no-store"); const emptyBody = empty.body as { claimed?: number; processed?: number }; assert((emptyBody.claimed ?? emptyBody.processed) === 0, "empty run claims zero");
    const eligible = await fixture("eligible", "temporary"); const valid = await fixture("valid", "valid"); const mismatch = await fixture("mismatch", "mismatch"); const notDue = await fixture("not-due", "temporary", "REFUND_FAILED_RETRYING", false); const completed = await fixture("completed", "temporary", "REFUND_COMPLETED"); const owner = await fixture("owner", "temporary", "OWNER_REVIEW_REQUIRED"); const foreign = await fixture("foreign", "temporary"); const foreignLease = await db.from("refund_workflows").update({ reconciliation_claim_token: randomUUID(), reconciliation_claimed_at: new Date().toISOString(), reconciliation_claim_expires_at: new Date(Date.now() + 3600000).toISOString() }).eq("id", foreign.workflowId); if (foreignLease.error) throw foreignLease.error;
    const mixed = await call(SECRET); assert(mixed.response.ok && mixed.response.headers.get("cache-control") === "no-store", "mixed HTTP success and no-store"); const body = mixed.body as { processed: number; results: Array<{ id: string; status: string }> }; assert(body.processed <= 50, "batch bound"); const result = new Map(body.results.map((x) => [x.id, x.status])); const labels = new Map([[eligible.workflowId, "eligible"], [valid.workflowId, "valid"], [mismatch.workflowId, "mismatch"], [notDue.workflowId, "not-due"], [completed.workflowId, "completed"], [owner.workflowId, "owner"], [foreign.workflowId, "foreign"]]); assert(!result.has(notDue.workflowId) && !result.has(completed.workflowId) && !result.has(owner.workflowId) && !result.has(foreign.workflowId), `excluded workflows not processed: ${JSON.stringify(body.results.map((item) => ({ label: labels.get(item.id), ...item })))}`); assert(result.get(valid.workflowId) === "REFUND_COMPLETED", "valid cancellation recovery converged"); assert(result.get(mismatch.workflowId) === "OWNER_REVIEW_REQUIRED", "mismatch escalated");
    const duplicate = await call(SECRET); assert(duplicate.response.ok, "duplicate request succeeds"); const concurrent = await Promise.all([call(SECRET), call(SECRET)]); assert(concurrent.every((r) => r.response.ok), "concurrent requests succeed");
    const extra = await Promise.all(Array.from({ length: 51 }, (_, i) => fixture(`batch-${i}`, "temporary"))); const bounded = await call(SECRET); const boundedBody = bounded.body as { processed: number }; assert(bounded.response.ok && boundedBody.processed <= 50, "51-fixture run remains bounded");
    const validEntitlement = (await db.from("entitlements").select("id").eq("user_id", valid.userId).eq("is_active", true)).data ?? []; const mismatchEntitlement = (await db.from("entitlements").select("id").eq("user_id", mismatch.userId).eq("is_active", true)).data ?? []; assert(validEntitlement.length === 0 && mismatchEntitlement.length === 1, "entitlement outcomes are safe");
    finalSummary = { unauthorizedBlocked: true, authorizedEmptyRun: "verified", mixedBatch: "verified", duplicateScheduler: "verified", concurrentScheduler: "verified", batchBound: "verified", notDueExcluded: true, completedExcluded: true, ownerReviewExcluded: true, foreignLeaseProtected: true, validRecoveryConverged: true, mismatchFailedClosed: true, responseSafety: "verified", providerLookupCalls, providerCancellationCalls, TossNetworkCalls: 0 };
    void eligible; void extra;
  } finally { if (next) { next.kill(); await new Promise<void>((resolve) => { const timer = setTimeout(resolve, 3000); next!.once("close", () => { clearTimeout(timer); resolve(); }); }); } if (mock) { mock.closeAllConnections(); await new Promise<void>((resolve) => mock!.close(() => resolve())); } await cleanup(); }
  if (finalSummary) process.stdout.write(`${JSON.stringify(finalSummary)}\n`);
}
main().catch((error: unknown) => { console.error(error); process.exitCode = 1; });
