import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const read = (path: string) => readFileSync(path, "utf8");
const mypage = read("app/mypage/page.tsx");
const support = read("app/support/SupportCenterClient.tsx");
const supportPage = read("app/support/page.tsx");
const supportServer = read("app/lib/support/server.ts");
const supportApi = read("app/api/support/requests/route.ts");
const refundApi = read("app/api/orders/[orderId]/refund/route.ts");
const refundWorkflow = read("app/lib/refunds/server.ts");
const terms = read("app/terms/page.tsx");
const refundPolicy = read("app/refund/page.tsx");
const checkout = read("app/checkout/[productId]/CheckoutAccessPanel.tsx");
const orderApi = read("app/api/orders/route.ts");

assert(mypage.includes("purchaseHistory.map((item)"), "all-profile historical payment ledger remains available");
assert(mypage.includes("item.refund.customerMessage") && mypage.includes("refundStatusLabels[item.refund.status]"), "existing refund statuses still shown");
assert(mypage.includes("category=PAYMENT_REFUND&orderId=${encodeURIComponent(item.orderId)}"), "mypage refund inquiry carries the exact order id");
assert(!mypage.includes("openRefundForm") && !mypage.includes("/api/orders/${encodeURIComponent(item.orderId)}/refund"), "mypage no longer submits financial mutation");
assert(supportPage.includes("getOrderForUser(orderId, user.id)") && supportPage.includes("listUserProfiles(user.id)"), "support order details resolved after authentication/ownership check");
assert(supportPage.includes("initialRefundOrder={refundOrder}") && supportPage.includes("invalidRefundOrder="), "verified order data and invalid order state are passed separately");
assert(support.includes("initialRefundOrder.productName") && support.includes("initialRefundOrder.profileLabel") && support.includes("initialRefundOrder.amount"), "order context presented without manual reentry");
assert(support.includes('category === "PAID_ANALYSIS" ? (') && support.includes("value={analysisOrderId}"), "only unrelated analysis support may ask for a legacy optional order reference");
assert(support.includes("const linkedOrderId = category === \"PAYMENT_REFUND\"") && support.includes("initialRefundOrder?.orderId ?? null"), "refund request must use the server-verified order reference");
assert(support.includes("orderId: linkedOrderId"), "only verified refund order reference reaches the existing support API");
assert(!support.includes('value={orderId}') && !support.includes('setOrderId(') && !support.includes("orderId.trim()"), "refund intake must not render or collect order ID from the customer");
assert(support.includes('category === "PAYMENT_REFUND" && invalidRefundOrder'), "invalid refund order blocks only refund submission");

assert(support.includes("initialCategory = null") && support.includes('useState(Boolean(initialCategory))'), "order-link opens refund intake directly");
for (const label of ["중복 결제 또는 결제 오류","리포트 미제공 또는 생성 오류","구매한 내용과 다른 리포트 제공","리포트 제공 전 구매 취소","기타 환불·결제 문의"]) assert(support.includes(label), `missing refund reason ${label}`);
assert(support.includes('category === "PAYMENT_REFUND" && !refundReason'), "refund request must include reason");
assert(support.includes("정상 제공된 리포트") && support.includes("법정 청약철회 권리"), "no blanket refusal of statutory rights");
assert(support.includes('fetch("/api/support/requests"') && !support.includes("cancelPaymentWithToss") && !support.includes("requestFullRefund"), "customer contact cannot mutate payments");
assert(supportServer.includes('.eq("user_id", user.id)') && supportServer.includes('.eq("order_id", orderId)'), "support request ownership and deduplication stay server-side");
assert(supportServer.includes('if (input.category === "PAYMENT_REFUND" && orderId)') && supportServer.includes('MAX_ACTIVE_REQUESTS && !(input.category === "PAYMENT_REFUND" && orderId)'), "distinct payment claims cannot be blocked solely by general support quota");
assert(supportApi.includes("createSupportRequest") && !supportApi.includes("cancelPaymentWithToss"), "support API is intake-only");
assert(refundApi.includes("REFUND_SUPPORT_REQUIRED") && refundApi.includes("getOrderForUser(orderId, user.id)"), "legacy refund endpoint redirects only owned orders");
assert(!refundApi.includes("requestFullRefund") && !refundApi.includes("cancelPaymentWithToss"), "legacy customer reason cannot initiate provider cancellation");
assert(refundWorkflow.includes("requestFullRefund(") && refundWorkflow.includes("reconcileRefundWorkflow("), "existing refund processing and reconciliation are not deleted");
assert(terms.includes("주관적 기대") && terms.includes("고객지원 센터(/support)") && terms.includes("소급하여 제한하지 않습니다"), "terms describe the same intake and retain previous legal rights");
assert(refundPolicy.includes("제공 개시") && refundPolicy.includes("실제 열람") && refundPolicy.includes("고객지원 센터(/support)") && refundPolicy.includes("소급하여 제한되지 않습니다"), "refund policy distinguishes delivery stages and preserves lawful rights");
assert(checkout.includes("구매 전 확인해 주세요") && checkout.includes("단순 변심에 따른 청약철회") && checkout.includes('href="/refund"'), "checkout shows compact pre-payment disclosure");
assert(checkout.includes("disabled={isPaying || !immediateGenerationAcknowledged}") && checkout.includes("immediateGenerationAcknowledged: true"), "checkout continues to block payment until acknowledgement");
assert(orderApi.includes("requestBody?.immediateGenerationAcknowledged !== true"), "backend still rejects orders lacking acknowledgement");
console.log("refund-support-checkout-policy-regression: OK");
