-- Admin growth analytics: privacy-minimized first-party operational metrics.
-- No names, birth data, analysis content, IP addresses, user agents, email addresses,
-- or auth user IDs are stored in the analytics event table.

create table if not exists public.service_analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  visitor_id uuid,
  actor_kind text,
  event_date_kst date not null default ((timezone('Asia/Seoul', now()))::date),
  occurred_at timestamptz not null default now(),
  constraint service_analytics_event_name_valid check (
    event_name in (
      'VISITOR_DAY',
      'FREE_ANALYSIS_STARTED',
      'FREE_ANALYSIS_COMPLETED',
      'SIGNUP_COMPLETED',
      'FREE_ANALYSIS_REFRESH_COMPLETED'
    )
  ),
  constraint service_analytics_actor_kind_valid check (
    actor_kind is null or actor_kind in ('guest', 'member')
  ),
  constraint service_analytics_visit_requires_visitor check (
    event_name <> 'VISITOR_DAY' or visitor_id is not null
  )
);

create unique index if not exists service_analytics_event_visitor_day_unique
  on public.service_analytics_events (event_name, visitor_id, event_date_kst);
create index if not exists service_analytics_event_date_idx
  on public.service_analytics_events (event_date_kst, event_name);
create index if not exists service_analytics_occurred_at_idx
  on public.service_analytics_events (occurred_at);

alter table public.service_analytics_events enable row level security;
revoke all on public.service_analytics_events from public, anon, authenticated;
grant select, insert on public.service_analytics_events to service_role;
grant usage, select on sequence public.service_analytics_events_id_seq to service_role;

create or replace function public.get_admin_growth_dashboard(p_days integer default 30)
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
with params as (
  select
    greatest(7, least(coalesce(p_days, 30), 90))::integer as days,
    (timezone('Asia/Seoul', now()))::date as today,
    date_trunc('week', timezone('Asia/Seoul', now()))::date as week_start,
    date_trunc('month', timezone('Asia/Seoul', now()))::date as month_start
),
days as (
  select generate_series(
    (select today - (days - 1) from params),
    (select today from params),
    interval '1 day'
  )::date as day
),
event_daily as (
  select
    event_date_kst as day,
    count(*) filter (where event_name = 'VISITOR_DAY')::integer as visitors,
    count(*) filter (where event_name = 'FREE_ANALYSIS_STARTED')::integer as free_started,
    count(*) filter (where event_name = 'FREE_ANALYSIS_COMPLETED')::integer as free_completed,
    count(*) filter (where event_name = 'FREE_ANALYSIS_COMPLETED' and actor_kind = 'guest')::integer as guest_free_completed,
    count(*) filter (where event_name = 'FREE_ANALYSIS_COMPLETED' and actor_kind = 'member')::integer as member_free_completed,
    count(*) filter (where event_name = 'SIGNUP_COMPLETED')::integer as signups,
    count(*) filter (where event_name = 'FREE_ANALYSIS_REFRESH_COMPLETED')::integer as monthly_refreshes
  from public.service_analytics_events
  where event_date_kst >= (select today - (days - 1) from params)
  group by event_date_kst
),
checkout_daily as (
  select
    (timezone('Asia/Seoul', created_at))::date as day,
    count(*)::integer as checkout_started
  from public.orders
  where created_at >= (((select today - (days - 1) from params)::timestamp at time zone 'Asia/Seoul'))
  group by 1
),
paid_daily as (
  select
    (timezone('Asia/Seoul', paid_at))::date as day,
    count(*)::integer as paid_orders,
    count(distinct user_id)::integer as paying_customers,
    coalesce(sum(amount), 0)::bigint as gross_revenue_krw
  from public.orders
  where status = 'paid'
    and paid_at is not null
    and paid_at >= (((select today - (days - 1) from params)::timestamp at time zone 'Asia/Seoul'))
  group by 1
),
refund_daily as (
  select
    (timezone('Asia/Seoul', completed_at))::date as day,
    count(*)::integer as refunds,
    coalesce(sum(requested_amount), 0)::bigint as refund_amount_krw
  from public.refund_workflows
  where status = 'REFUND_COMPLETED'
    and completed_at is not null
    and completed_at >= (((select today - (days - 1) from params)::timestamp at time zone 'Asia/Seoul'))
  group by 1
),
adult_daily as (
  select
    (timezone('Asia/Seoul', paid_eligible_at))::date as day,
    count(*)::integer as adult_verified
  from public.account_lifecycles
  where paid_eligible_at is not null
    and paid_eligible_at >= (((select today - (days - 1) from params)::timestamp at time zone 'Asia/Seoul'))
  group by 1
),
daily as (
  select
    d.day,
    coalesce(e.visitors, 0) as visitors,
    coalesce(e.free_started, 0) as free_started,
    coalesce(e.free_completed, 0) as free_completed,
    coalesce(e.guest_free_completed, 0) as guest_free_completed,
    coalesce(e.member_free_completed, 0) as member_free_completed,
    coalesce(e.signups, 0) as signups,
    coalesce(e.monthly_refreshes, 0) as monthly_refreshes,
    coalesce(a.adult_verified, 0) as adult_verified,
    coalesce(c.checkout_started, 0) as checkout_started,
    coalesce(p.paid_orders, 0) as paid_orders,
    coalesce(p.paying_customers, 0) as paying_customers,
    coalesce(p.gross_revenue_krw, 0) as gross_revenue_krw,
    coalesce(r.refunds, 0) as refunds,
    coalesce(r.refund_amount_krw, 0) as refund_amount_krw,
    coalesce(p.gross_revenue_krw, 0) - coalesce(r.refund_amount_krw, 0) as net_revenue_krw
  from days d
  left join event_daily e on e.day = d.day
  left join adult_daily a on a.day = d.day
  left join checkout_daily c on c.day = d.day
  left join paid_daily p on p.day = d.day
  left join refund_daily r on r.day = d.day
  order by d.day
),
periods as (
  select 'today'::text as name, today as start_day, today as end_day from params
  union all
  select 'week', week_start, today from params
  union all
  select 'month', month_start, today from params
),
period_event as (
  select
    p.name,
    count(*) filter (where e.event_name = 'VISITOR_DAY')::integer as visitors,
    count(*) filter (where e.event_name = 'FREE_ANALYSIS_STARTED')::integer as free_started,
    count(*) filter (where e.event_name = 'FREE_ANALYSIS_COMPLETED')::integer as free_completed,
    count(*) filter (where e.event_name = 'SIGNUP_COMPLETED')::integer as signups,
    count(*) filter (where e.event_name = 'FREE_ANALYSIS_REFRESH_COMPLETED')::integer as monthly_refreshes
  from periods p
  left join public.service_analytics_events e
    on e.event_date_kst between p.start_day and p.end_day
  group by p.name
),
period_adult as (
  select p.name, count(a.*)::integer as adult_verified
  from periods p
  left join public.account_lifecycles a
    on a.paid_eligible_at is not null
   and (timezone('Asia/Seoul', a.paid_eligible_at))::date between p.start_day and p.end_day
  group by p.name
),
period_checkout as (
  select p.name, count(o.*)::integer as checkout_started
  from periods p
  left join public.orders o
    on (timezone('Asia/Seoul', o.created_at))::date between p.start_day and p.end_day
  group by p.name
),
period_paid as (
  select
    p.name,
    count(o.*)::integer as paid_orders,
    count(distinct o.user_id)::integer as paying_customers,
    coalesce(sum(o.amount), 0)::bigint as gross_revenue_krw
  from periods p
  left join public.orders o
    on o.status = 'paid'
   and o.paid_at is not null
   and (timezone('Asia/Seoul', o.paid_at))::date between p.start_day and p.end_day
  group by p.name
),
period_refund as (
  select
    p.name,
    count(r.*)::integer as refunds,
    coalesce(sum(r.requested_amount), 0)::bigint as refund_amount_krw
  from periods p
  left join public.refund_workflows r
    on r.status = 'REFUND_COMPLETED'
   and r.completed_at is not null
   and (timezone('Asia/Seoul', r.completed_at))::date between p.start_day and p.end_day
  group by p.name
),
period_json as (
  select jsonb_object_agg(
    p.name,
    jsonb_build_object(
      'startDate', p.start_day,
      'endDate', p.end_day,
      'visitors', coalesce(e.visitors, 0),
      'freeAnalysisStarted', coalesce(e.free_started, 0),
      'freeAnalysisCompleted', coalesce(e.free_completed, 0),
      'signups', coalesce(e.signups, 0),
      'adultVerified', coalesce(a.adult_verified, 0),
      'monthlyRefreshes', coalesce(e.monthly_refreshes, 0),
      'checkoutStarted', coalesce(c.checkout_started, 0),
      'paidOrders', coalesce(pd.paid_orders, 0),
      'payingCustomers', coalesce(pd.paying_customers, 0),
      'grossRevenueKrw', coalesce(pd.gross_revenue_krw, 0),
      'refunds', coalesce(r.refunds, 0),
      'refundAmountKrw', coalesce(r.refund_amount_krw, 0),
      'netRevenueKrw', coalesce(pd.gross_revenue_krw, 0) - coalesce(r.refund_amount_krw, 0)
    )
  ) as value
  from periods p
  left join period_event e on e.name = p.name
  left join period_adult a on a.name = p.name
  left join period_checkout c on c.name = p.name
  left join period_paid pd on pd.name = p.name
  left join period_refund r on r.name = p.name
),
totals as (
  select jsonb_build_object(
    'dataSince', (select min(occurred_at) from public.service_analytics_events),
    'visitors', (select count(distinct visitor_id)::integer from public.service_analytics_events where event_name = 'VISITOR_DAY'),
    'freeAnalysisStarted', (select count(*)::integer from public.service_analytics_events where event_name = 'FREE_ANALYSIS_STARTED'),
    'freeAnalysisCompleted', (select count(*)::integer from public.service_analytics_events where event_name = 'FREE_ANALYSIS_COMPLETED'),
    'signups', (select count(*)::integer from public.service_analytics_events where event_name = 'SIGNUP_COMPLETED'),
    'monthlyRefreshes', (select count(*)::integer from public.service_analytics_events where event_name = 'FREE_ANALYSIS_REFRESH_COMPLETED'),
    'activeAccounts', (select count(*)::integer from public.account_lifecycles where status = 'ACTIVE'),
    'currentVerifiedAdults', (select count(*)::integer from public.account_lifecycles where status = 'ACTIVE' and paid_eligibility_status = 'VERIFIED_ADULT'),
    'adultVerifiedEver', (select count(*)::integer from public.account_lifecycles where paid_eligible_at is not null),
    'checkoutStarted', (select count(*)::integer from public.orders),
    'paidOrders', (select count(*)::integer from public.orders where status = 'paid' and paid_at is not null),
    'payingCustomers', (select count(distinct user_id)::integer from public.orders where status = 'paid' and paid_at is not null),
    'grossRevenueKrw', (select coalesce(sum(amount), 0)::bigint from public.orders where status = 'paid' and paid_at is not null),
    'refunds', (select count(*)::integer from public.refund_workflows where status = 'REFUND_COMPLETED' and completed_at is not null),
    'refundAmountKrw', (select coalesce(sum(requested_amount), 0)::bigint from public.refund_workflows where status = 'REFUND_COMPLETED' and completed_at is not null),
    'netRevenueKrw',
      (select coalesce(sum(amount), 0)::bigint from public.orders where status = 'paid' and paid_at is not null)
      - (select coalesce(sum(requested_amount), 0)::bigint from public.refund_workflows where status = 'REFUND_COMPLETED' and completed_at is not null)
  ) as value
),
top_products as (
  select jsonb_agg(
    jsonb_build_object(
      'productId', x.product_id,
      'paidOrders', x.paid_orders,
      'grossRevenueKrw', x.gross_revenue_krw,
      'refundAmountKrw', x.refund_amount_krw,
      'netRevenueKrw', x.gross_revenue_krw - x.refund_amount_krw
    ) order by (x.gross_revenue_krw - x.refund_amount_krw) desc, x.product_id
  ) as value
  from (
    select
      o.product_id,
      count(*)::integer as paid_orders,
      coalesce(sum(o.amount), 0)::bigint as gross_revenue_krw,
      coalesce((select sum(r.requested_amount) from public.refund_workflows r where r.product_id = o.product_id and r.status = 'REFUND_COMPLETED'), 0)::bigint as refund_amount_krw
    from public.orders o
    where o.status = 'paid' and o.paid_at is not null
    group by o.product_id
    order by (coalesce(sum(o.amount), 0) - coalesce((select sum(r.requested_amount) from public.refund_workflows r where r.product_id = o.product_id and r.status = 'REFUND_COMPLETED'), 0)) desc
    limit 10
  ) x
)
select jsonb_build_object(
  'generatedAt', now(),
  'timezone', 'Asia/Seoul',
  'rangeDays', (select days from params),
  'daily', coalesce((select jsonb_agg(jsonb_build_object(
    'date', day,
    'visitors', visitors,
    'freeAnalysisStarted', free_started,
    'freeAnalysisCompleted', free_completed,
    'guestFreeAnalysisCompleted', guest_free_completed,
    'memberFreeAnalysisCompleted', member_free_completed,
    'signups', signups,
    'adultVerified', adult_verified,
    'monthlyRefreshes', monthly_refreshes,
    'checkoutStarted', checkout_started,
    'paidOrders', paid_orders,
    'payingCustomers', paying_customers,
    'grossRevenueKrw', gross_revenue_krw,
    'refunds', refunds,
    'refundAmountKrw', refund_amount_krw,
    'netRevenueKrw', net_revenue_krw
  ) order by day) from daily), '[]'::jsonb),
  'periods', coalesce((select value from period_json), '{}'::jsonb),
  'totals', coalesce((select value from totals), '{}'::jsonb),
  'topProducts', coalesce((select value from top_products), '[]'::jsonb)
);
$$;

revoke all on function public.get_admin_growth_dashboard(integer) from public, anon, authenticated;
grant execute on function public.get_admin_growth_dashboard(integer) to service_role;
